server:
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

spring:
  application:
    name: ${APP_NAME}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    addresses: ${QUEUE_ADDRESS}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${BREVO_SMTP_LOGIN}
    password: ${BREVO_SMTP_KEY}
    test-connection: ${MAIL_TEST_CONNECTION}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH}
          connectiontimeout: ${MAIL_SMTP_CONNECTION_TIMEOUT}
          timeout: ${MAIL_SMTP_TIMEOUT}
          writetimeout: ${MAIL_SMTP_WRITE_TIMEOUT}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE}
            required: ${MAIL_SMTP_STARTTLS_REQUIRED}

app:
  frontend:
    base-url: ${FRONTEND_BASE_URL}
  security:
    jwt:
      issuer: ${JWT_ISSUER}
      expiration-seconds: ${JWT_EXPIRATION_SECONDS}
      secret: ${JWT_SECRET}
  mail:
    enabled: ${MAIL_ENABLED}
    validate-on-startup: ${MAIL_VALIDATE_ON_STARTUP}
    from: ${BREVO_MAIL_FROM}
    app-name: ${APP_MAIL_NAME}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
